log:
  timestampFormat: 2006-01-02 15:04:05
  level: debug
  # file:
  #   path: /var/log/xiuexcel/xiuexcel.log

excel:
  sourceFile: D:\test_data\分部门利润表模板.xlsx
  sourceSheet: Sheet1
  destinationDirectory: D:\excel_file\